# Generated by Django 3.1.1 on 2020-09-28 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=10)),
                ('rank', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('reply', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('hit', models.IntegerField()),
                ('like', models.IntegerField()),
                ('site', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='issue.community')),
            ],
        ),
    ]
