# Generated by Django 3.1.1 on 2020-09-28 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='url',
            new_name='link',
        ),
    ]
