# Generated by Django 3.1.1 on 2020-09-28 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_auto_20200928_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='link',
            new_name='url',
        ),
    ]
