# Generated by Django 3.1.1 on 2020-10-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20200928_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='site',
            field=models.CharField(choices=[('pp', 'ppomppu'), ('cl', 'clien'), ('ou', 'todayhumor')], max_length=10),
        ),
    ]
