# Generated by Django 3.1.1 on 2020-10-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_auto_20201005_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='site',
            field=models.CharField(choices=[('pp', '뽐뿌'), ('cl', '클리앙'), ('ou', '오유')], max_length=10),
        ),
    ]
