# Generated by Django 3.1.1 on 2020-10-15 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0008_auto_20201005_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='site',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='issue.community'),
        ),
    ]
